name: Deploy Canary Build
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    branches: main
    paths:
      - src/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  RELEASE_TAG: canary
  RELEASE_TITLE: Canary Build
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [win-x64, linux-x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: |
          dotnet publish --self-contained --runtime ${{ matrix.platform }} --output build
          $artifacts = (Get-ChildItem -Path build -Recurse).FullName
          New-Item -Path artifacts -ItemType Directory
          Compress-Archive -Path $artifacts -DestinationPath artifacts/${{ github.event.repository.name }}_${{ matrix.platform }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: artifacts/*
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          name: ${{ env.RELEASE_TITLE }}
          tag_name: ${{ env.RELEASE_TAG }}