name: Canary
on:
  push:
    paths:
      - CraftMine/**
  workflow_dispatch:
concurrency:
  group: release
  cancel-in-progress: true
env:
  RELEASE_TAG: Canary
jobs:
  main:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Publish Project
        run: |
          dotnet publish -c Release -p:WindowsPackageType=None -p:Platform=x64 -p:RuntimeIdentifier=win10-x64 -o build/x64
          dotnet publish -c Release -p:WindowsPackageType=None -p:Platform=x86 -p:RuntimeIdentifier=win10-x86 -o build/x86
          dotnet publish -c Release -p:WindowsPackageType=None -p:Platform=arm64 -p:RuntimeIdentifier=win10-arm64 -o build/arm64
          $x64artifacts = (Get-ChildItem -Recurse -Path build/x64/*).FullName
          $x86artifacts = (Get-ChildItem -Recurse -Path build/x86/*).FullName
          $arm64artifacts = (Get-ChildItem -Recurse -Path build/arm64/*).FullName
          Compress-Archive -Path $x64artifacts -DestinationPath ${{ github.event.repository.name }}_windows-x64.zip
          Compress-Archive -Path $x86artifacts -DestinationPath ${{ github.event.repository.name }}_windows-x86.zip
          Compress-Archive -Path $arm64artifacts -DestinationPath ${{ github.event.repository.name }}_windows-arm64.zip
      - name: Delete (Existing) Release Tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
      - name: Deploy Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}_windows-x64.zip,${{ github.event.repository.name }}_windows-x86.zip,${{ github.event.repository.name }}_windows-arm64.zip"
          prerelease: true
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ github.event.repository.default_branch }}