name: Canary Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    paths:
      - src/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  PROJECT_FILE: src/Shulkerbox/Shulkerbox.csproj
  RELEASE_TAG: Canary
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Install Signing Certificate
        run: |
          $bytes = [System.Convert]::FromBase64String("${{ secrets.SIGNING_CERTIFICATE }}")
          [IO.File]::WriteAllBytes("certificate.pfx", $bytes)
          $password = ConvertTo-SecureString ${{ secrets.SIGNING_KEY }} -AsPlainText
          Import-PfxCertificate certificate.pfx -CertStoreLocation "Cert:\CurrentUser\My" -Password $password
          $thumbprint = (Get-PfxCertificate Certificate.pfx -Password $password).Thumbprint
          Write-Output -InputObject "SIGNING_THUMBPRINT=$thumbprint" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Publish Project
        run: |
          dotnet publish ${{ env.PROJECT_FILE }} --configuration Release -p:Platform=x64 -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateThumbprint=${{ env.SIGNING_THUMBPRINT }} -p:AppxPackageDir=${{ github.workspace }}/packages/
          $artifact = (Get-ChildItem ${{ github.workspace }}/packages/*_Test/*.msix).FullName | Select-Object -First 1
          New-Item -Path artifacts -ItemType Directory
          Move-Item -Path $artifact -Destination artifacts/${{ github.event.repository.name }}_windows.msix
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: artifacts
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Output
          path: artifacts
      - name: Delete (Existing) Releases
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
      - name: Release Artifacts
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: true
          files: artifacts/*