name: Canary Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    paths:
      - src/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  TARGET_FILE: Shulkerbox.sln
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Publish App
        run: |
          dotnet publish --configuration Release --output build
          $artifacts = (Get-ChildItem -Path build/*).FullName
          New-Item -ItemType Directory -Path artifacts
          Compress-Archive -Path $artifacts -DestinationPath artifacts/${{ github.event.repository.name }}.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: artifacts
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Output
          path: artifacts
      - name: Deploy Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: canary
          title: Canary
          files: artifacts/*