name: Deploy Canary Build
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    branches: main
    paths:
      - src/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    uses: dentolos19/dentolos19/.github/workflows/build-dotnet.yml@main
    strategy:
      matrix:
        runtime-platform: [win-x64, linux-x64]
    with:
      project_name: Shulkerbox
      project_file: Shulkerbox.sln
      runtime_platform: ${{ matrix.runtime-platform }}
      executable_file: Shulkerbox.Desktop.exe
  deploy:
    needs: build
    uses: dentolos19/dentolos19/.github/workflows/deploy-artifacts.yml@main
    permissions:
      contents: write
    secrets: inherit
    with:
      release_title: Canary
      release_tag: canary